package agents_engine.ksp

import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSValueParameter
import com.google.devtools.ksp.symbol.Modifier
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets

/**
 * `agents-kt-ksp/agents_engine/ksp/AgentsKtSymbolProcessor.kt` — KSP
 * processor entry (#1018). Runtime `GenerableSupport` reads emitted
 * objects via `Class.forName`, falls back to reflection.
 *
 * **Two passes per round:**
 *
 * 1. **Validation** (#1700) — walk every `@Generable` class, run shape rules
 *    (sealed/abstract/etc.) and field-type rules (#1701: every primary-ctor
 *    param must be a supported type). Violations land via
 *    `env.logger.error(message, symbol)`.
 *
 * 2. **Schema generation** (#1701) — for clean non-sealed data classes,
 *    emit `<package>/<ClassName>__GeneratedSchema.kt` containing a
 *    `const val JSON_SCHEMA: String` built by [SchemaEmitter],
 *    `LLM_DESCRIPTION` by [LlmDescriptionEmitter] (#1703), and
 *    `constructFromMap` by [ConstructFromMapEmitter] (#1704). The runtime
 *    looks up these objects via `Class.forName` (see
 *    `agents_engine.generation.GenerableSupport.kt`) and falls back to
 *    reflection when not present.
 *
 * Sealed roots are deliberately skipped this iteration — variant schema
 * with `type` discriminator is a separate emitter; the runtime path stays
 * authoritative for sealed for now.
 *
 * See `src/main/resources/internals-agent/ksp/AgentsKtSymbolProcessor.md`
 * in the main module for the adjunct surfaced via the InternalsAgent
 * (#1837 / #1895).
 */
class AgentsKtSymbolProcessor(
    private val env: SymbolProcessorEnvironment,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val generables = resolver
            .getSymbolsWithAnnotation(GENERABLE_FQN)
            .filterIsInstance<KSClassDeclaration>()

        for (cls in generables) {
            val model = cls.toGenerableClass(resolver)
            val errors = GenerableValidator.validate(model)
            errors.forEach { msg -> env.logger.error(msg, cls) }
            if (errors.isEmpty() && SchemaEmitter.canEmit(model)) {
                writeGeneratedSchema(cls, model)
            }
        }

        return emptyList()
    }

    private fun writeGeneratedSchema(cls: KSClassDeclaration, model: GenerableValidator.GenerableClass) {
        val simpleName = cls.simpleName.asString()
        val packageName = cls.packageName.asString()
        val generatedName = "${simpleName}__GeneratedSchema"
        // #1702: sealed parents emit oneOf; data classes emit object.
        // The runtime lookup mechanism is shape-agnostic — it just reads
        // the named constants.
        val schema = if (model.isSealed) {
            SchemaEmitter.emitSealedSchema(model)
        } else {
            SchemaEmitter.emitDataClassSchema(model)
        }
        // #1703: emit toLlmDescription markdown into the same generated
        // object as a second const. Runtime checks both via the generalised
        // GeneratedMetaCache lookup. The emitter handles the
        // @LlmDescription override internally — when present it returns
        // the override verbatim.
        val llmDescription = if (model.isSealed) {
            LlmDescriptionEmitter.emitSealed(model)
        } else {
            LlmDescriptionEmitter.emitDataClass(model)
        }

        // #1704: emit constructFromMap when eligible. Sealed parents always
        // emit a dispatch body; data classes only when they have no
        // default-valued params. Falls through to runtime reflection otherwise.
        val constructFromMapBody = if (ConstructFromMapEmitter.canGenerate(model)) {
            if (model.isSealed) {
                ConstructFromMapEmitter.emitSealedDispatchBody(model)
            } else {
                // The processor knows whether THIS class is a sealed-variant
                // by checking its supertypes via KSP.
                val isVariant = cls.isSealedVariant()
                ConstructFromMapEmitter.emitDataClassBody(model, isVariant)
            }
        } else null

        val source = buildString {
            if (packageName.isNotEmpty()) appendLine("package $packageName")
            appendLine()
            appendLine("// Generated by agents-kt-ksp (#1701, #1702, #1703, #1704). Do not edit.")
            appendLine("// Looked up at runtime by GenerableSupport.kt to skip the reflection walk.")
            appendLine()
            appendLine("internal object $generatedName {")
            appendLine("    const val JSON_SCHEMA: String = \"\"\"$schema\"\"\"")
            // Multi-line strings inside Kotlin's raw-string literal need their
            // own `"""` delimiter — we already use `"""` for the outer, so
            // the safest path is a double-quoted string with escapes. The
            // description text already has literal `\n` rendered (it's a
            // String with embedded newlines from buildString.appendLine).
            appendLine("    const val LLM_DESCRIPTION: String = ${quoteForKotlinSource(llmDescription)}")
            if (constructFromMapBody != null) {
                appendLine()
                appendLine("    @JvmStatic")
                appendLine("    fun constructFromMap(fields: Map<*, Any?>): ${model.qualifiedName}? {")
                // Indent every line of the emitter's body by 8 spaces (object
                // is at 0, method body at 4, body content at 8). Blank lines
                // stay blank — preserves any visual breaks the emitter may
                // produce.
                constructFromMapBody.lineSequence().forEach { line ->
                    if (line.isEmpty()) appendLine() else appendLine("        $line")
                }
                appendLine("    }")
            }
            appendLine("}")
        }

        // Dependencies: aggregating=false (one input → one output), source
        // file is the @Generable class itself. KSP uses this for
        // incremental compilation — when only this class changes, only its
        // generated file is rebuilt.
        val deps = Dependencies(aggregating = false, sources = arrayOf(cls.containingFile!!))
        env.codeGenerator
            .createNewFile(deps, packageName, generatedName, extensionName = "kt")
            .use { stream ->
                OutputStreamWriter(stream, StandardCharsets.UTF_8).use { w -> w.write(source) }
            }
    }

    /**
     * Emit a Kotlin string literal that, when compiled, produces exactly
     * [text]. Uses standard `"..."` form with escapes — works for any input,
     * including text that contains `"""`. We deliberately don't use
     * triple-quoted raw strings for [text] because the runtime
     * `toLlmDescription` output can contain embedded `"""` in user-provided
     * `@Generable(description)` or `@Guide` text, which would close a raw
     * literal prematurely.
     */
    private fun quoteForKotlinSource(text: String): String = buildString {
        append('"')
        text.forEach { c ->
            when (c) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                '$' -> append("\\$")  // suppress Kotlin string interpolation
                else -> append(c)
            }
        }
        append('"')
    }

    // ── KSP → data-model mapping ───────────────────────────────────────────

    private fun KSClassDeclaration.toGenerableClass(resolver: Resolver): GenerableValidator.GenerableClass {
        val params = primaryConstructor?.parameters.orEmpty()
        val isSealed = Modifier.SEALED in modifiers
        // #1702: walk sealed subclasses so emitSealedSchema can render the
        // oneOf wrapper. KSP returns variants visible to the current
        // compilation; cross-module setups would produce an incomplete list
        // (separate follow-up to detect-and-skip).
        val variants = if (isSealed) {
            getSealedSubclasses().map { it.toVariantClass(resolver) }.toList()
        } else emptyList()
        return GenerableValidator.GenerableClass(
            qualifiedName = qualifiedName?.asString() ?: simpleName.asString(),
            isSealed = isSealed,
            isAbstract = Modifier.ABSTRACT in modifiers,
            isInterface = classKind == ClassKind.INTERFACE,
            isEnum = classKind == ClassKind.ENUM_CLASS,
            isAnnotation = classKind == ClassKind.ANNOTATION_CLASS,
            hasPrimaryConstructor = primaryConstructor != null,
            primaryConstructorParamCount = params.size,
            fields = params.map { it.toField(resolver) },
            simpleName = simpleName.asString(),
            guideDescription = readClassGuideDescription(),
            sealedVariants = variants,
            generableDescription = readGenerableDescription(),
            llmDescriptionOverride = readLlmDescriptionOverride(),
        )
    }

    /**
     * Variant-shaped projection of a [KSClassDeclaration] for sealed
     * children (#1702). The processor doesn't recurse — variants are leaves
     * for the parent's emitter and validate / emit on their own in the
     * main walk.
     */
    private fun KSClassDeclaration.toVariantClass(resolver: Resolver): GenerableValidator.GenerableClass {
        val params = primaryConstructor?.parameters.orEmpty()
        return GenerableValidator.GenerableClass(
            qualifiedName = qualifiedName?.asString() ?: simpleName.asString(),
            isSealed = Modifier.SEALED in modifiers,
            isAbstract = Modifier.ABSTRACT in modifiers,
            isInterface = classKind == ClassKind.INTERFACE,
            isEnum = classKind == ClassKind.ENUM_CLASS,
            isAnnotation = classKind == ClassKind.ANNOTATION_CLASS,
            hasPrimaryConstructor = primaryConstructor != null,
            primaryConstructorParamCount = params.size,
            fields = params.map { it.toField(resolver) },
            simpleName = simpleName.asString(),
            guideDescription = readClassGuideDescription(),
        )
    }

    /**
     * True if this class is a direct subclass of a sealed `@Generable` root
     * (#1704). The generated `constructFromMap` then allows `"type"` as an
     * extra key and verifies the discriminator value.
     */
    private fun KSClassDeclaration.isSealedVariant(): Boolean =
        superTypes.any { superType ->
            val decl = superType.resolve().declaration
            decl is KSClassDeclaration && Modifier.SEALED in decl.modifiers
        }

    /** @Guide annotation directly on the class — used as the variant `description`. */
    private fun KSClassDeclaration.readClassGuideDescription(): String? =
        annotations
            .firstOrNull {
                it.shortName.asString() == "Guide" &&
                    it.annotationType.resolve().declaration.qualifiedName?.asString() == GUIDE_FQN
            }
            ?.arguments
            ?.firstOrNull { it.name?.asString() == "description" }
            ?.value as? String

    /** @Generable(description) — class-level intro text rendered as a paragraph after the header. */
    private fun KSClassDeclaration.readGenerableDescription(): String =
        annotations
            .firstOrNull {
                it.shortName.asString() == "Generable" &&
                    it.annotationType.resolve().declaration.qualifiedName?.asString() == GENERABLE_FQN
            }
            ?.arguments
            ?.firstOrNull { it.name?.asString() == "description" }
            ?.value as? String
            ?: ""

    /** @LlmDescription(text) — replaces all auto-generated text when present. */
    private fun KSClassDeclaration.readLlmDescriptionOverride(): String? =
        annotations
            .firstOrNull {
                it.shortName.asString() == "LlmDescription" &&
                    it.annotationType.resolve().declaration.qualifiedName?.asString() == LLM_DESCRIPTION_FQN
            }
            ?.arguments
            ?.firstOrNull { it.name?.asString() == "text" }
            ?.value as? String

    private fun KSValueParameter.toField(resolver: Resolver): GenerableValidator.Field {
        val ksType = type.resolve()
        val typeKind = ksType.toFieldType(resolver)
        return GenerableValidator.Field(
            name = name?.asString() ?: "_anon",
            type = typeKind,
            isNullable = ksType.isMarkedNullable,
            hasDefault = hasDefault,
            guideDescription = readGuideDescription(),
        )
    }

    private fun KSValueParameter.readGuideDescription(): String? =
        annotations
            .firstOrNull { it.shortName.asString() == "Guide" && it.annotationType.resolve()
                .declaration.qualifiedName?.asString() == GUIDE_FQN }
            ?.arguments
            ?.firstOrNull { it.name?.asString() == "description" }
            ?.value as? String

    private fun KSType.toFieldType(resolver: Resolver): GenerableValidator.FieldType {
        val decl = declaration
        val fqn = decl.qualifiedName?.asString() ?: return GenerableValidator.FieldType.Unsupported(
            decl.simpleName.asString(),
        )
        return when (fqn) {
            "kotlin.String" -> GenerableValidator.FieldType.StringT
            "kotlin.Int" -> GenerableValidator.FieldType.IntT
            "kotlin.Long" -> GenerableValidator.FieldType.LongT
            "kotlin.Double" -> GenerableValidator.FieldType.DoubleT
            "kotlin.Float" -> GenerableValidator.FieldType.FloatT
            "kotlin.Boolean" -> GenerableValidator.FieldType.BoolT
            "kotlin.collections.List" -> {
                val itemKs = arguments.firstOrNull()?.type?.resolve()
                val itemKind = itemKs?.toFieldType(resolver)
                GenerableValidator.FieldType.ListT(itemKind)
            }
            else -> {
                // Nested @Generable reference — accept; the runtime resolves
                // the nested schema at lookup time. Anything else is
                // unsupported and rolls up as a validator error.
                val isGenerable = decl is KSClassDeclaration && decl.annotations.any {
                    it.annotationType.resolve().declaration.qualifiedName?.asString() == GENERABLE_FQN
                }
                if (isGenerable) GenerableValidator.FieldType.GenerableRef(fqn)
                else GenerableValidator.FieldType.Unsupported(fqn)
            }
        }
    }

    private companion object {
        const val GENERABLE_FQN = "agents_engine.generation.Generable"
        const val GUIDE_FQN = "agents_engine.generation.Guide"
        const val LLM_DESCRIPTION_FQN = "agents_engine.generation.LlmDescription"
    }
}
