package agents_engine.model

import agents_engine.content.BlobStore
import agents_engine.content.Content
import agents_engine.content.ImageMime
import agents_engine.generation.LenientJsonParser
import agents_engine.mcp.McpJson
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.time.Duration
import java.util.Base64

/**
 * #3867.b — OpenAI Images adapter (`POST /v1/images/generations`,
 * `b64_json`). Generated bytes are stored in [blobStore]; the typed
 * [Content.Image] ref travels through the agent graph like any other
 * attachment. `baseUrl` is injectable for stub-server tests.
 */
class OpenAiImagesClient(
    private val apiKey: String,
    private val blobStore: BlobStore,
    private val model: String = "gpt-image-1",
    private val size: String = "1024x1024",
    private val baseUrl: String = "https://api.openai.com",
    private val httpClient: HttpClient = HttpClient.newHttpClient(),
    timeoutSeconds: Long = DEFAULT_TIMEOUT_SECONDS,
) : ImageModelClient {

    private val timeout = Duration.ofSeconds(timeoutSeconds)

    override fun generate(prompt: String): Content.Image {
        val body = """{"model":${McpJson.encode(model)},"prompt":${McpJson.encode(prompt)},""" +
            """"size":${McpJson.encode(size)},"response_format":"b64_json"}"""
        val request = HttpRequest.newBuilder(URI.create("$baseUrl/v1/images/generations"))
            .timeout(timeout)
            .header("Content-Type", "application/json")
            .header("Authorization", "Bearer $apiKey")
            .POST(HttpRequest.BodyPublishers.ofString(body))
            .build()
        val response = httpClient.send(request, HttpResponse.BodyHandlers.ofString())
        check(response.statusCode() == HTTP_OK) {
            "OpenAI Images returned HTTP ${response.statusCode()}: ${response.body().take(ERROR_PREVIEW)}"
        }
        val parsed = LenientJsonParser.parse(response.body()) as? Map<*, *>
            ?: error("OpenAI Images returned non-JSON: ${response.body().take(ERROR_PREVIEW)}")
        val b64 = ((parsed["data"] as? List<*>)?.firstOrNull() as? Map<*, *>)?.get("b64_json") as? String
            ?: error("OpenAI Images response missing data[0].b64_json: $parsed")
        val bytes = Base64.getDecoder().decode(b64)
        val ref = blobStore.put(bytes, ImageMime.Png.wireMime)
        return Content.Image(ref = ref, mime = ImageMime.Png)
    }

    private companion object {
        const val HTTP_OK = 200
        const val ERROR_PREVIEW = 200
        const val DEFAULT_TIMEOUT_SECONDS = 120L
    }
}
