package agents_engine.model

import agents_engine.content.AudioMime
import agents_engine.content.Content
import agents_engine.content.ImageMime
import agents_engine.content.InMemoryBlobStore
import com.sun.net.httpserver.HttpServer
import java.net.InetSocketAddress
import java.util.Base64
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

// #3867 — STT / image generation / TTS against a local stub server:
// wire shapes pinned, bytes round-trip through the BlobStore, and the
// acceptance flow (audio -> transcript -> image -> typed Content.Image).

class MultimodalClientsTest {

    private val requests = mutableListOf<Pair<String, ByteArray>>()
    private val server: HttpServer = HttpServer.create(InetSocketAddress("127.0.0.1", 0), 0).apply {
        createContext("/v1/audio/transcriptions") { ex ->
            requests.add(ex.requestURI.path to ex.requestBody.readBytes())
            respond(ex, """{"text":"draw a lighthouse at dusk"}""".toByteArray(), "application/json")
        }
        createContext("/v1/images/generations") { ex ->
            requests.add(ex.requestURI.path to ex.requestBody.readBytes())
            val b64 = Base64.getEncoder().encodeToString("png-bytes".toByteArray())
            respond(ex, """{"data":[{"b64_json":"$b64"}]}""".toByteArray(), "application/json")
        }
        createContext("/v1/audio/speech") { ex ->
            requests.add(ex.requestURI.path to ex.requestBody.readBytes())
            respond(ex, "mp3-bytes".toByteArray(), "audio/mpeg")
        }
        executor = null
        start()
    }

    private fun respond(ex: com.sun.net.httpserver.HttpExchange, body: ByteArray, mime: String) {
        ex.responseHeaders.add("Content-Type", mime)
        ex.sendResponseHeaders(200, body.size.toLong())
        ex.responseBody.use { it.write(body) }
        ex.close()
    }

    private val baseUrl get() = "http://localhost:${server.address.port}"

    @AfterTest
    fun stop() = server.stop(0)

    @Test
    fun `acceptance flow — transcribe audio, generate an image, emit typed Content`() {
        val blobs = InMemoryBlobStore()
        val audioRef = blobs.put("fake-wav".toByteArray(), AudioMime.Wav.wireMime)
        val audio = Content.Audio(ref = audioRef, mime = AudioMime.Wav)

        val transcript = OpenAiSpeechToTextClient("k", baseUrl = baseUrl).transcribe(audio, blobs)
        assertEquals("draw a lighthouse at dusk", transcript)

        val image = OpenAiImagesClient("k", blobs, baseUrl = baseUrl).generate(transcript)
        assertEquals(ImageMime.Png, image.mime)
        assertEquals("png-bytes", String(blobs.get(image.ref)!!), "generated bytes land in the BlobStore")
    }

    @Test
    fun `whisper request is well-formed multipart carrying model and audio bytes`() {
        val blobs = InMemoryBlobStore()
        val ref = blobs.put("RIFFdata".toByteArray(), AudioMime.Wav.wireMime)
        OpenAiSpeechToTextClient("k", baseUrl = baseUrl)
            .transcribe(Content.Audio(ref = ref, mime = AudioMime.Wav), blobs)

        val body = String(requests.last().second, Charsets.ISO_8859_1)
        assertTrue("name=\"model\"" in body && "whisper-1" in body, "model part present")
        assertTrue("filename=\"audio.wav\"" in body && "RIFFdata" in body, "file part carries the bytes")
    }

    @Test
    fun `tts returns a typed Content Audio with bytes in the store`() {
        val blobs = InMemoryBlobStore()
        val audio = OpenAiTtsClient("k", blobs, baseUrl = baseUrl).speak("hello world")

        assertEquals(AudioMime.Mp3, audio.mime)
        assertEquals("mp3-bytes", String(blobs.get(audio.ref)!!))
        val request = String(requests.last().second)
        assertTrue("\"input\":\"hello world\"" in request && "\"voice\"" in request, request)
    }
}
