// SPDX-License-Identifier: Apache-2.0
// #4520 — VENDORED from agntcy/dir search/v1/record_query.proto (faithful: no buf/validate). java_* options added for codegen.
syntax = "proto3";

package agntcy.dir.search.v1;

option java_package = "agntcy.dir.search.v1";
option java_multiple_files = true;

message RecordQuery {
  RecordQueryType type = 1;
  string value = 2;
}

enum RecordQueryType {
  RECORD_QUERY_TYPE_UNSPECIFIED = 0;
  RECORD_QUERY_TYPE_NAME = 1;
  RECORD_QUERY_TYPE_VERSION = 2;
  RECORD_QUERY_TYPE_SKILL_ID = 3;
  RECORD_QUERY_TYPE_SKILL_NAME = 4;
  RECORD_QUERY_TYPE_LOCATOR = 5;
  RECORD_QUERY_TYPE_MODULE_NAME = 6;
  RECORD_QUERY_TYPE_DOMAIN_ID = 7;
  RECORD_QUERY_TYPE_DOMAIN_NAME = 8;
  RECORD_QUERY_TYPE_CREATED_AT = 9;
  RECORD_QUERY_TYPE_AUTHOR = 10;
  RECORD_QUERY_TYPE_SCHEMA_VERSION = 11;
  RECORD_QUERY_TYPE_MODULE_ID = 12;
  RECORD_QUERY_TYPE_VERIFIED = 13;
  RECORD_QUERY_TYPE_TRUSTED = 14;
  RECORD_QUERY_TYPE_ANNOTATION = 15;
}
