#!/usr/bin/env bash
#
# Regenerates gradle/verification-metadata.xml after a dependency or Gradle
# update. Run this whenever you:
#   - bump a dependency version in build.gradle.kts
#   - bump the Gradle wrapper (./gradlew wrapper --gradle-version=X)
#   - add or remove a plugin
#   - see a "Checksums are missing from verification metadata" report
#
# Why this exists:
# Supply-chain attacks are real. We pin every artifact byte via SHA256 in
# gradle/verification-metadata.xml so a malicious upstream pushing
# backdoored 2.3.22 can't substitute itself for the locked 2.3.21. But
# Gradle's `--write-verification-metadata` only sees what the invoked task
# resolves, so calling it with `help` misses the plugin classpath, the
# test classpath, etc. This script invokes a task list that covers ALL
# resolution paths the project actually uses.
#
# Sources/javadoc jars are exempted via <trusted-artifacts> in the
# metadata file (they don't execute, only the IDE reads them); see #858
# for the rationale.
#
# Usage:
#   ./scripts/update-verification-metadata.sh
#
# After running:
#   git diff gradle/verification-metadata.xml   # review
#   git add gradle/verification-metadata.xml    # if happy
#
# To revert:
#   git restore gradle/verification-metadata.xml
#
set -euo pipefail

cd "$(dirname "$0")/.."

METADATA="gradle/verification-metadata.xml"

if [ ! -f "$METADATA" ]; then
    echo "error: $METADATA not found — are you in the project root?" >&2
    exit 1
fi

BACKUP=$(mktemp)
cp "$METADATA" "$BACKUP"
trap 'rm -f "$BACKUP"' EXIT

echo "→ Snapshotting current $METADATA"
echo "→ Regenerating with --write-verification-metadata sha256"
echo "  (this re-resolves the dependency graph; first run after a Gradle"
echo "   update can take a few minutes as Maven Central is hit fresh)"
echo

# The task list below covers every classpath the project actually uses:
#  - help                        : trivial, but resolves the build classpath
#  - :dependencies --all-configurations : enumerates every project config without
#                                running it (covers compileClasspath,
#                                testCompileClasspath, plus Kotlin compiler
#                                plugin classpaths)
#  - :buildEnvironment           : enumerates the build classpath (Gradle plugins
#                                themselves and their transitive deps)
#  - :compileKotlin :compileTestKotlin : forces actual resolution of the
#                                compilation paths
#
# --refresh-dependencies forces re-download from Maven Central so the SHAs
# match upstream bytes (not stale cache from a different machine).
./gradlew \
    --write-verification-metadata sha256 \
    --refresh-dependencies \
    help \
    :dependencies --configuration runtimeClasspath \
    :buildEnvironment \
    :compileKotlin \
    :compileTestKotlin

# Defensive: confirm the trusted-artifacts block survived. Gradle's merge
# behavior is supposed to preserve the <configuration> block, but if a
# future Gradle version regresses we want a loud signal, not a quiet
# rollback to "verify everything including sources".
if ! grep -q "trusted-artifacts" "$METADATA"; then
    echo
    echo "⚠ <trusted-artifacts> block is missing from the regenerated file." >&2
    echo "  Restoring from backup. Investigate the regeneration step." >&2
    cp "$BACKUP" "$METADATA"
    exit 2
fi

echo
echo "─────────────────────────────────────────────────────────"

if cmp -s "$BACKUP" "$METADATA"; then
    echo "✓ No changes — verification metadata is up to date."
    exit 0
fi

ADDED=$(diff "$BACKUP" "$METADATA" | grep -c "^>" || true)
REMOVED=$(diff "$BACKUP" "$METADATA" | grep -c "^<" || true)

echo "→ Diff summary: $ADDED added line(s), $REMOVED removed line(s)"
echo
echo "Review the changes:"
echo "  git diff $METADATA"
echo
echo "If the new entries look reasonable (only artifacts you expected to"
echo "appear, with origin=\"Generated by Gradle\"):"
echo "  git add $METADATA"
echo
echo "If anything looks off (unexpected components, removed entries,"
echo "missing trusted-artifacts):"
echo "  git restore $METADATA"
